name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
    tags:
      - '[0-9].[0-9].[0-9]'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] #, windows-2019, macOS-11]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v3

      - name: Install CI Build Wheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build Wheels
        run: cd eigs-py && python -m cibuildwheel --output-dir ../wheelhouse && cd -

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
