name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] #, windows-2019, macOS-11]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: cd eigs-py && python -m cibuildwheel --output-dir ../wheelhouse && cd -
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: flaport/manylinux2014_x86_64
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
